### ISSUE TITLE
jekyll's recipe seems to have a too loose requirement on concurrent-ruby

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/rb-jekyll-feedstock#8]
It currently resolves with  1.1.6 while jekyll really requires 1.0.x.

**Comment by SylvainCorlay** [comment]
```
(base) sylvain@mbp ~/dev/QuantStack/quantstack.github.io (master +)$ jekyll serve
Traceback (most recent call last):
	12: from /home/sylvain/mambaforge/bin/jekyll:23:in `<main>'
	11: from /home/sylvain/mambaforge/lib/ruby/2.5.0/rubygems.rb:304:in `activate_bin_path'
	10: from /home/sylvain/mambaforge/lib/ruby/2.5.0/rubygems.rb:304:in `synchronize'
	 9: from /home/sylvain/mambaforge/lib/ruby/2.5.0/rubygems.rb:305:in `block in activate_bin_path'
	 8: from /home/sylvain/mambaforge/lib/ruby/2.5.0/rubygems/specification.rb:1440:in `activate'
	 7: from /home/sylvain/mambaforge/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `activate_dependencies'
	 6: from /home/sylvain/mambaforge/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `each'
	 5: from /home/sylvain/mambaforge/lib/ruby/2.5.0/rubygems/specification.rb:1472:in `block in activate_dependencies'
	 4: from /home/sylvain/mambaforge/lib/ruby/2.5.0/rubygems/specification.rb:1440:in `activate'
	 3: from /home/sylvain/mambaforge/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `activate_dependencies'
	 2: from /home/sylvain/mambaforge/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `each'
	 1: from /home/sylvain/mambaforge/lib/ruby/2.5.0/rubygems/specification.rb:1469:in `block in activate_dependencies'
/home/sylvain/mambaforge/lib/ruby/2.5.0/rubygems/dependency.rb:310:in `to_specs': Could not find 'concurrent-ruby' (~> 1.0) among 52 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/home/sylvain/.gem/ruby/2.5.0:/home/sylvain/mambaforge/lib/ruby/gems/2.5.0', execute `gem env` for more information
```
